### PR TITLE
RFC for Bioschemas Governance 1.0

### PR DESCRIPTION
**Pull request by AlasdairGray**
This pull request corresponds to the request for comments of the 1.0 release of the Bioschemas Governance. The community will be given a period of 4 weeks, i.e. until 23 April, to comment on the governance model.

The current leadership team will respond to comments made either in this pull request, on the mailing list, or through the issue tracker and make relevant changes. 

The current leadership team will then vote, requiring a 2/3 majority with 80% attendance, on whether to accept the governance model or close this pull request in light of further refinement being needed.

### CODE REVIEW

**Comment by AlasdairGray** [comment]
@CaroleGoble @nsjuty @ljgarcia @sarala Please do not approve this PR until we have a leadership meeting after 23 April to discuss any community comments.

**Review by egonw — CHANGES_REQUESTED** [review]
Comments to earlier versions that do not automatically show up:

* https://github.com/BioSchemas/governance/commit/a856d9e32d4f570075c6be58ea7dea09423c0335#r38673246

The rest looks fine to me.

**Comment by AlasdairGray** [comment]
#3 seeks clarification on the voting for governance change

**Comment by AlasdairGray** [comment]
@egonw are you happy with the link to the election process that I added in in commit 
bb4ca4b?

**Comment by egonw** [comment]
> @egonw are you happy with the link to the election process that I added in in commit
> [bb4ca4b](https://github.com/BioSchemas/governance/commit/bb4ca4b17d55e6a5b8143b5e9e4d43f71556987a)?

Yeah, looks good.

**Review by egonw — APPROVED** [review]

**Comment by AlasdairGray** [comment]
Approved at management group call on 2 June 2020 ([minutes](https://docs.google.com/document/d/1lzBcNZPy6s-Sqk9gA3ACGZpz2FyfcFqPHXf37S0bZLE/edit?usp=sharing))

**Pull request merged**
